VERSION = 0.01
MCU_NAME = atmega2560
F_CPU = 16000000
TARGET		= bassboycc
PACKAGES  = avrlib bassboycc
PROGRAMMER_PORT = /dev/tty.usbmodem1411
PROGRAMMER = wiring
AVRDUDE_ERASE = yes
AVRDUDE_LOCK = no

EXTRA_DEFINES =

include avrlib/makefile.mk

include $(DEP_FILE)
